<script type="text/javascript">
//<![CDATA[
	if (typeof TM == 'undefined') TM = {};
	TM.QuickShop = {
		BASE_URL : '<?php echo str_replace("index.php/","",$this->getUrl()) ?>',
		QS_FRM_WIDTH : 860,
		QS_FRM_HEIGHT : 550,
		QS_IMG: '<?php echo $this->getSkinUrl('images/quickshop/tm_quickshop_preview.png'); ?>',
		QS_IMGH: '<?php echo $this->getSkinUrl('images/quickshop/tm_quickshop_preview_hover.png'); ?>'
	};
//]]	
</script> 
