<?php $async = Mage::getStoreConfig('magebird_popup/settings/asynchronous') ? 'async' : ''; ?>
<?php if(Mage::app()->getStore()->isCurrentlySecure()): ?>
  <?php if(Mage::getStoreConfig('magebird_popup/settings/load_jquery')): ?>
  <script <?php echo $async; ?> type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebird_popup/jquery.js', array('_secure' => true,'_nosid' => true)); ?>"></script>
  <?php endif;?>
  <script <?php echo $async; ?> type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebird_popup/main.js', array('_secure' => true,'_nosid' => true)); ?>?v=1.4.4__previewId=<?php echo $this->getPreviewId() ? $this->getPreviewId() : 0; ?>__templateId=<?php echo $this->getTemplateId() ? $this->getTemplateId() : 0;?>__popup_page_id=<?php echo $this->getTargetPageId() ? $this->getTargetPageId() : 0; ?>__filterId=<?php echo $this->getFilterId() ? $this->getFilterId() : 0; ?>__secure=1__baseUrl=<?php echo urlencode(str_replace("https://","",Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true))); ?>__isAjax=<?php echo $this->isAjax()?>__requestType=<?php echo $this->requestType()?>__"></script>        
<?php else:?>
  <?php if(Mage::getStoreConfig('magebird_popup/settings/load_jquery')): ?>
  <script <?php echo $async; ?> type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebird_popup/jquery.js') ?>"></script>
  <?php endif;?>
  <script <?php echo $async; ?> type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebird_popup/main.js') ?>?v=1.4.4__previewId=<?php echo $this->getPreviewId() ? $this->getPreviewId() : 0;?>__templateId=<?php echo $this->getTemplateId() ? $this->getTemplateId() : 0; ?>__popup_page_id=<?php echo $this->getTargetPageId() ? $this->getTargetPageId() : 0; ?>__filterId=<?php echo $this->getFilterId() ? $this->getFilterId() : 0; ?>__secure=0__baseUrl=<?php echo urlencode(str_replace("http://","",Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK))); ?>__isAjax=<?php echo $this->isAjax()?>__requestType=<?php echo $this->requestType()?>__"></script>
<?php endif; ?> 
