
<?php $_brand = $this->getBrand(); ?>
 
<?php $processor = Mage::helper('zeon_brand')->getBlockTemplateProcessor(); ?>

<?php $_products = $this->getProductCollection(); ?>

<div class="middle_main">
    <div class="">  
        <div class="">

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div class="row">  
                    <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12">

                        <div class="row">
                            <div class="col-lg-10 col-md-10 col-xs-10 col-sm-10">
                                <div class="picture_details_wrap new">

                                    <?php echo $this->getLayout()->createBlock('zeon_brand/view')->setTemplate('zeon/brand/sliderbrand.phtml')->toHtml(); ?></div>

                            </div>

                        </div>

                        <div class="row">
                            <div class="col-lg-10 col-md-10 col-xs-12 col-sm-10">  
                                <div class="col-lg-9 col-md-9 col-xs-12 col-sm-9">
                                    <div class="row brand_expert_slider">
                                        <!--<div class="picture_details_wrap new">

                                            <div class="picture_details">
                                                <h1>NEW PRODUCT</h1>
                                                <h2><span>Something really cool about that product</span></h2>
                                            </div>
										</div>-->
											<div id="myCarousel" class="carousel slide" data-ride="carousel">
											  <?php   
													/* Akash Kumar Updated 29 April 2015 */
													$brand_code=  $_brand->getBrand(); 
													$brands = Mage::getResourceModel('zeon_brand/brand_collection')->addFieldToFilter('brand',$brand_code)->getFirstItem();								
												?>
												
													<ol class="carousel-indicators">
														
															<li class="" data-slide-to="0" data-target="#myCarousel"></li>
														
															<li class="" data-slide-to="1" data-target="#myCarousel"></li>
														
															<li class="" data-slide-to="2" data-target="#myCarousel"></li>
														
															<li class="" data-slide-to="3" data-target="#myCarousel"></li>
														
															<li class="" data-slide-to="4" data-target="#myCarousel"></li>
														
															<li class="" data-slide-to="5" data-target="#myCarousel"></li>
														
															<li class="" data-slide-to="6" data-target="#myCarousel"></li>	
													</ol>	
													<div class="carousel-inner" role="listbox">					
														<div class="item active">						
															<?php if($brands->getBrandImage() && $brands->getBrandImage() !=''){ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/'.$brands->getBrandImage(); ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php } ?>
														</div>	
														<div class="item">	
															<?php if($brands->getBrandImage1() && $brands->getBrandImage1() !=''){ ?>
															<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php } ?>
														</div>	
														<div class="item">	
															<?php if($brands->getBrandImage2() && $brands->getBrandImage2() !=''){ ?>
															<img src="<?php echo Mage::getUrl('media').'brand/'.$brands->getBrandImage2(); ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php } ?>
														</div>	
														<div class="item">		
															<?php if($brands->getBrandImage3() && $brands->getBrandImage3() !=''){ ?>
															<img src="<?php echo Mage::getUrl('media').'brand/'.$brands->getBrandImage3(); ?>" alt="<?php echo $brands->getIdentifier(); ?>" />				
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php } ?>
														</div>	
														<div class="item">	
															<?php if($brands->getBrandImage4() && $brands->getBrandImage4() !=''){ ?>
															<img src="<?php echo Mage::getUrl('media').'brand/'.$brands->getBrandImage4(); ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php } ?>
														</div>	
														<div class="item">	
															<?php if($brands->getBrandImage5() && $brands->getBrandImage5() !=''){ ?>
															<img src="<?php echo Mage::getUrl('media').'brand/'.$brands->getBrandImage5(); ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />				
															<?php } ?>
														</div>	
														<div class="item">	
															<?php if($brands->getBrandImage6() && $brands->getBrandImage6() !=''){ ?>
															<img src="<?php echo Mage::getUrl('media').'brand/'.$brands->getBrandImage6(); ?>" alt="<?php echo $brands->getIdentifier(); ?>" />					
															<?php }else{ ?>
																<img src="<?php echo Mage::getUrl('media').'brand/aa1.png'; ?>" alt="<?php echo $brands->getIdentifier(); ?>" />				
															<?php } ?>	
														</div>	
															
														
													</div>
													  
													<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
													  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
													  <span class="sr-only">Previous</span>
													</a>
													<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
													  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
													  <span class="sr-only">Next</span>
													</a>
													</div>	
									</div>
                                </div>

                                <div class="col-lg-3 col-md-3 col-xs-12 col-sm-3">

                                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('slider10')->toHtml() ?>                                </div>


                            </div>

                        </div>


                        <div class="clearfix"></div>

                        <div class="row">
                            <div class="sure_product_heading">

                            </div>
                        </div>

                        <?php $_brand = $this->getBrand(); ?>
                        <?php $processor = Mage::helper('zeon_brand')->getBlockTemplateProcessor(); ?>

                        <div class="category-view">
                            <div class="clearfix" style="margin-bottom: 1px";>

                            </div>
                            <?php echo $this->getToolbarHtml() ?>
                            <div class="category-products">
                                <?php if (($_products = $this->getProductCollection()) && $_collectionSize = count($_products)): ?>

                                    <?php $_columnCount = $this->getColumnCount(); ?>
                                    <?php
                                    $i = 0;
                                    foreach ($_products as $product):
                                        ?>
                                        <?php $_product = Mage::getModel('catalog/product')->load($product['entity_id']); ?>
                                            <?php if ($i++ % $_columnCount == 0): ?>
                                            <ul class="products-grid first odd">
											<?php endif ?>
                                            <li class="col-lg-4 col-md-4 col-sm-6 col-xs-12<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                                                <div class="product_box">
                                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                                        <div product_wrap" align="center">
                                                             <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>" width="184" height="165" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                                        </div>
                                                    </a>

                                                    <div class="product_detail_wrap">
                                                        <div class="social_show">

                                                            <div class="social_icon">
                                                                <span class="icon-heart icon-md"></span>
                                                            </div>

                                                            <div class="social_icon">
                                                                <span class="icon-facebook icon-md"></span>
                                                            </div>
                                                            <div class="social_icon">
                                                                <span class="icon-twitter icon-md"></span>
                                                            </div>
                                                            <div class="social_icon">
                                                                <span class="icon-pinterest icon-md"></span>
                                                            </div>
                                                            <div class="social_icon">
                                                                <span class="icon-envelope icon-md"></span>
                                                            </div>
                                                        </div>
                                                        <?php
                                                        $productName = $_product->getName();
                                                        if (strlen($productName) > 35) {
                                                            $productName = substr($productName, 0, 32) . '...';
                                                        }
                                                        ?>
                                                        <h1><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($productName) ?> </a></h1>
                                                        <h2> By <?php echo Mage::getModel('zeon_brand/brand')->getBrandName($_brand->getBrand(), Mage::app()->getStore()->getId()) ?></h2>
                                                        <h2><span><?php echo $this->getPriceHtml($_product, true) ?></span></h2>
                                                    </div>
                                                </div>
                                            </li>
                                        <?php if ($i % $_columnCount == 0 || $i == count($_products)): ?>
                                            </ul>
                                        <?php endif ?>
                                    <?php endforeach ?>

								<?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">

                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<?php //zend_debug::dump($_brand->getBrandBanner());exit; ?>
                                <?php if ($_brand->getBrandBanner()): ?>
                                    <a href="<?php echo $this->getUrl('brand' . '/' . $_brand->getIdentifier()) ?>">
										<img alt="<?php echo $_brand->getBrandBanner() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'brand' . '/' . $_brand->getBrandBanner() ?>" height="91" width="208">
									</a>
								<?php endif; ?>
                            </div>
							<?php if($_brand->getDisplayAuthorizedDealer()){ ?>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . '/brand/defentive.png'; ?>" alt="">
							</div>
							<?php } ?>
                        </div>

                        <div class="clearfix"></div>

                        <div class="shure_wrap">							
                            <h1><?php echo $_brand->getIdentifier(); ?></h1>
                            <p><?php echo $processor->filter($_brand->getDescription()); ?></p>

                        </div>

                        <div class="shure_text">
                            <p>   
								<?php echo $processor->filter($_brand->getDescription1()); ?>
                            </p>
                        </div>

						<div class="clearfix"></div>
						<!-- Akash Kumar Updated 27 MAy 2015 -->
						<?php //echo $processor->filter($_brand->getDescription2()); ?> 
						<div class="shure_wrap">
							<h1 class="buzz">Brand Buzz:</h1>
						</div>
						<div class="buzz_field">
							<div class="row">
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
									<div class="buz_box"><img src="<?php echo $this->getSkinUrl('images/buzz1.png') ?>" alt="" /></div>
								</div>
								<div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
									<div class="buz_right">
										<p><?php echo $this->getLayout()->createBlock('zeon_brand/view')->setTemplate('zeon/brand/brand_event.phtml') ?></p>
										<p><?php echo $this->getLayout()->createBlock("zeon_brand/view")->setTemplate("zeon/brand/brand_event.phtml")->toHtml(); ?></p>	
									</div>
								</div>
							</div>
						</div>
						
						
						<?php $brand_reviews= $this->getBrandReview($_brand->getBrand()); ?>
						<?php if(!empty($brand_reviews)){ ?>
						<div class="shure_wrap">
							<h1 class="buzz"><?php echo $this->__('Brand Reviews :') ?></h1>
						</div>
						<div class="buzz_field">
							<div class="row">
								<div class="jcarousel-wrapper">
									<div class="jcarousel">
										<ul>
											<?php   foreach($brand_reviews as $key=>$review) { 
											$product = Mage::getModel('catalog/product')->load($review['product_id']);
											$productMediaConfig = Mage::getModel('catalog/product_media_config');
											$baseImageUrl = $productMediaConfig->getMediaUrl($product->getSmallImage());
											?>	
											<li>
												<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
													<div class="buz_box"><img class="brandreview_img" style="width:50px;" src="<?php echo $baseImageUrl ?>" alt="<?php echo $product->getName(); ?>" /></div>
												</div>
												<div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
													<div class="buz_right">
														<div class="brand_reviews_content row">	
															<div class="col-md-3 col-sm-3 col-xs-3">															
																<div class="col-md-6 col-sm-6 col-xs-6 review_text1">
																	<p><?php echo $review['detail']; ?></p>
																</div>
																<div class="rating-box col-md-3 col-sm-3 col-xs-3">
																	<div class="rating" style="width:<?php echo $review['percent'] ?>%;"></div>
																</div>
															</div>
														</div>
												    </div>
												</div>
											</li>
											<?php } ?>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<?php } ?>
											
                    </div>
                </div>
            </div>

        </div>

    </div>
</div> 


<?php echo $processor->filter($_brand->getBrandEvent()); ?>
<style type="text/css">
.brand_reviews{
	display:inline-block;
}
.review_text1{
  padding-left: 0px;
  padding-right: 0px;
}
.rating-box {
    background: rgba(0, 0, 0, 0) url(<?php echo $this->getSkinUrl('images').'/product_rating_blank_star.gif' ?>) repeat-x scroll 0 0;
    float: left;
    height: 16px;
    margin-left: 10px;
    position: relative;
    width: 69px;
}

.rating-box .rating {
    background: rgba(0, 0, 0, 0) url(<?php echo $this->getSkinUrl('images').'/product_rating_full_star.gif'?>) repeat-x scroll 0 0;
    height: 16px;
    left: 0;
    position: absolute;
    top: 0;
}
</style>
<script type="text/javascript" src="<?php echo Mage::getUrl('skin').'js/jcarousel.responsive.js'; ?>"></script>
<script type="text/javascript" src="<?php echo Mage::getUrl('skin').'js/jquery.jcarousel.min.js'; ?>"></script>