<script type="text/javascript">  
jQuery('head').append('<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/magebird_popup/widget/newsletter/global.css?v=1.4.4') ?>" type="text/css" />');
var workingText = '<?php echo $this->__('Working')?>...';
<?php
if(Mage::app()->getStore()->isCurrentlySecure()){
  $subscribeUrl = Mage::getUrl('magebird_popup/newsletter/subscribe', array('_forced_secure' => true));         
}else{
  $subscribeUrl = Mage::getUrl('magebird_popup/newsletter/subscribe');
}
?>
var subscribeUrl = '<?php echo $subscribeUrl ?>';
var url = "<?php echo $this->getSkinUrl('js/magebird_popup/newsletter.js') ?>";
jQuery.getScript(url); 
</script>
<!--DONT REMOVE! jQuery use it to check if css is loaded-->
<div class="cssLoadedChecker moctod-dribegam"></div>
<div class="cssLoadedChecker2 moctod-dribegam"></div>
